### ISSUE TITLE
Uncaught RangeError: Invalid array length

### ISSUE THREAD

**Issue by yshestakov** [mcpride/atom-mdtoc#8]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-mdtoc](https://github.com/mcpride/atom-mdtoc) package 0.8.3

### Stack Trace

Uncaught RangeError: Invalid array length

```
At /Users/yshestakov/.atom/packages/atom-mdtoc/lib/toc-view.coffee:219

RangeError: Invalid array length
    at String.module.exports.String.repeat (/packages/atom-mdtoc/lib/toc-view.coffee:219:27)
    at LineNumberGutterComponent.render (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3221:43)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:107:40)
    at LineNumberGutterComponent.update (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3185:18)
    at updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at GutterContainerComponent.update (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:3076:18)
    at updateComponent (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:52:19)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:16:25)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at updateChildren (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:77:13)
    at patch (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/patch.js:18:15)
    at Object.updateSync (/Applications/Atom.app/Contents/Resources/app/node_modules/etch/lib/component-helpers.js:116:26)
    at TextEditorComponent.updateSyncBeforeMeasuringContent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:392:16)
    at TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:275:16)
    at etch.getScheduler.updateDocument (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:225:46)
    at ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:238:13)
```

### Commands

```
     -0:14.5.0 core:backspace (input.hidden-input)
     -0:12.4.0 core:save (input.hidden-input)
     -0:11.4.0 command-palette:toggle (input.hidden-input)
     -0:03.7.0 atom-mdtoc:insert (input.hidden-input)
```

### Non-Core Packages

```
atom-mdtoc 0.8.3 
markdown-image-assistant 0.2.1 
markdown-pdf 2.2.0 
markdown-toc 0.4.2 
```

**Comment by black-snow** [comment]
I just hit this, too.
Win 10 Pro, Atom 1.32.1
